server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

logging:
  level: info


database:
  # Connection info
  driverClass: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:file:~/temp/vaultdb;hsqldb.write_delay=false
  user: sa
  password:
  # Health checks
  validationQuery: "select 1 from INFORMATION_SCHEMA.SYSTEM_USERS"
  validationQueryTimeout: 3s